### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by jessevl** [comerc/selectize-placecomplete#1]
Hi, thanks for the suggestion earlier to check this project out, I've converted all select boxes from select2 to selectize and I like what I'm seeing so far. I cannot however figure out how to use your plugin. I'm sure I must be missing something obvious but I cannot figure out the instructions and more specifically the formatting of your usage example. Is his some sort of syntax I don't know of or is half the syntax missing? This is what I gathered it should've been but apparently I'm not deducting correctly:

``` javascript
                $(".citypicker").selectize({
                    mode: "single",
                    openOnFocus: false,
                    delimiter: null,
                    onInitialize: {
                        function(){
                            value = this.getValue();
                            place_id = $(".citypicker']").val();
                            this.updateOption(value){
                                value: value,
                                text: value,
                                description: value,
                                place_id: place_id
                            }
                        },  
                    },    
                    plugins: {
                        ['placecomplete']: {
                            selectDetails: function(placeResult){
                                $(".citypicker").val(placeResult.place_id);
                                return null;
                            }
                        }}
                })
```

**Comment by comerc** [comment]
Your code with errors. Please use http://js2coffee.org

**Comment by jessevl** [comment]
Coffeescript, I should've seen that!

Anyway, I now got the following error from the Google API: "TypeError: window.initPlacecomplete2 is not a function". In the code you request a callback to initplacecomplete2 but it should be without the 2, then it works perfectly. (I guess this is a leftover from some testing you've done?)

**Comment by comerc** [comment]
Try now, thanks.

**Comment by jessevl** [comment]
Yes I already did change that myself and it works perfectly, thanks! awesome work
